name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Connect to NetBird
        uses: Alemiz112/netbird-connect@v1.0.1
        with:
          setup-key: ${{ secrets.NETBIRD_SETUP_KEY }}
          hostname: github-actions-deploy
          management-url: https://api.netbird.io:443

      - name: Wait for NetBird
        run: |
          sleep 10
          netbird status
          ping -c 3 ${{ secrets.SERVER_HOST }} || true

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh

          printf "%s" "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh \
            -i ~/.ssh/id_ed25519 \
            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} <<'EOF'
              cd ~/repositories/Mirroring-Easy-Accounting-GTE
              git pull origin main
              docker compose up -d --build
          EOF
